import os
import uuid
import io
from datetime import datetime, date, timedelta
from sqlalchemy.orm import Session
from sqlalchemy import func
from fpdf import FPDF
from application.models import User, Farm, Acre, Zone, IrrigationLog, NodeData, Device, Report, ReportType, ReportStatus
from application.schemas.report import DynamicReportRequest, ReportModule, ReportTheme
from pydantic import UUID4

# PDF base class for components
class DynamicFarmPDF(FPDF):
    def __init__(self):
        super().__init__()
        self.set_auto_page_break(auto=True, margin=15)
        self.alias_nb_pages()

    def footer(self):
        self.set_y(-15)
        self.set_font('helvetica', 'I', 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10, f'Page {self.page_no()}/{{nb}} - Generated by AquaSol Dynamic Intelligence', 0, 0, 'C')

class ReportService:
    # ─── MODULE HANDLERS ─────────────────────────────────────────────────────────

    @staticmethod
    def _handle_header(pdf, farm, user, start_date, end_date):
        pdf.set_font('helvetica', 'B', 20)
        pdf.set_text_color(46, 125, 50)
        pdf.cell(0, 15, 'AquaSol Farm Diary', 0, 1, 'L')
        
        pdf.set_font('helvetica', 'B', 10)
        pdf.set_text_color(100, 100, 100)
        pdf.cell(0, 5, f'Period: {start_date.date()} to {end_date.date()}', 0, 1, 'L')
        pdf.ln(5)
        
        pdf.set_font('helvetica', 'B', 12)
        pdf.set_text_color(0, 0, 0)
        pdf.set_fill_color(240, 240, 240)
        pdf.cell(0, 10, 'Farmer & Farm Profile', 0, 1, 'L', fill=True)
        pdf.ln(2)
        
        pdf.set_font('helvetica', 'B', 10)
        pdf.cell(40, 7, 'Farmer:', 0, 0)
        pdf.set_font('helvetica', '', 10)
        pdf.cell(0, 7, user.name or "N/A", 0, 1)
        
        pdf.set_font('helvetica', 'B', 10)
        pdf.cell(40, 7, 'Farm Name:', 0, 0)
        pdf.set_font('helvetica', '', 10)
        pdf.cell(0, 7, farm.name, 0, 1)
        
        pdf.set_font('helvetica', 'B', 10)
        pdf.cell(40, 7, 'Location:', 0, 0)
        pdf.set_font('helvetica', '', 10)
        pdf.cell(0, 7, farm.location or "N/A", 0, 1)
        pdf.ln(10)

    @staticmethod
    def _handle_stat_cards(pdf, total_water, total_duration, logs_count):
        pdf.set_font('helvetica', 'B', 12)
        pdf.set_fill_color(240, 240, 240)
        pdf.cell(0, 10, 'Operational Summary', 0, 1, 'L', fill=True)
        pdf.ln(2)
        
        # Grid layout for stats
        pdf.set_font('helvetica', 'B', 10)
        pdf.cell(60, 10, 'Total Water Used', 1, 0, 'C')
        pdf.cell(60, 10, 'Total Duration', 1, 0, 'C')
        pdf.cell(60, 10, 'Total Events', 1, 1, 'C')
        
        pdf.set_font('helvetica', '', 14)
        pdf.set_text_color(46, 125, 50)
        pdf.cell(60, 15, f'{total_water:.1f} L', 1, 0, 'C')
        pdf.cell(60, 15, f'{total_duration:.1f} M', 1, 0, 'C')
        pdf.cell(60, 15, f'{logs_count}', 1, 1, 'C')
        pdf.set_text_color(0, 0, 0)
        pdf.ln(10)

    @staticmethod
    def _handle_chart_water(pdf, logs, report_id):
        if not logs: return
        import matplotlib.pyplot as plt
        try:
            usage_by_day = {}
            for log in logs:
                day = log.start_time.date()
                usage_by_day[day] = usage_by_day.get(day, 0) + (log.water_used or 0)
            
            days = sorted(usage_by_day.keys())
            values = [usage_by_day[d] for d in days]
            
            plt.figure(figsize=(8, 4))
            plt.bar([d.strftime('%m-%d') for d in days], values, color='#4CAF50')
            plt.title('Daily Water Consumption Trend', fontsize=12)
            plt.tight_layout()
            
            img_buf = io.BytesIO()
            plt.savefig(img_buf, format='png', dpi=100)
            plt.close()
            
            temp_chart = f"temp_water_{report_id}.png"
            with open(temp_chart, "wb") as f:
                f.write(img_buf.getbuffer())
                
            pdf.set_font('helvetica', 'B', 12)
            pdf.cell(0, 10, 'Water Usage Trends', 0, 1, 'L')
            pdf.image(temp_chart, x=15, w=180)
            os.remove(temp_chart)
            pdf.ln(10)
        except Exception as e:
            print(f"Chart Water failed: {e}")

    @staticmethod
    def _handle_table_zones(pdf, db, zones, start_date, end_date):
        pdf.set_font('helvetica', 'B', 12)
        pdf.set_fill_color(240, 240, 240)
        pdf.cell(0, 10, 'Zone-wise Performance', 0, 1, 'L', fill=True)
        pdf.ln(2)
        
        pdf.set_font('helvetica', 'B', 9)
        pdf.cell(40, 7, 'Zone Name', 1)
        pdf.cell(30, 7, 'Crop', 1)
        pdf.cell(30, 7, 'Soil', 1)
        pdf.cell(30, 7, 'Avg Moisture', 1)
        pdf.cell(50, 7, 'Status', 1)
        pdf.ln()
        
        pdf.set_font('helvetica', '', 9)
        for zone in zones:
            avg_m = db.query(func.avg(NodeData.soil_moisture)).join(Device).filter(
                Device.zone_id == zone.id,
                NodeData.timestamp >= start_date,
                NodeData.timestamp <= end_date
            ).scalar() or 0.0
            
            pdf.cell(40, 7, zone.name[:18], 1)
            pdf.cell(30, 7, zone.crop_type or "N/A", 1)
            pdf.cell(30, 7, zone.soil_type or "N/A", 1)
            pdf.cell(30, 7, f"{avg_m:.1f}%", 1)
            status = "Harvested" if zone.harvest_date and zone.harvest_date <= end_date else "Active"
            pdf.cell(50, 7, status, 1)
            pdf.ln()
        pdf.ln(10)

    @staticmethod
    def _handle_certification(pdf):
        pdf.set_font('helvetica', 'B', 10)
        pdf.cell(0, 10, 'Official Declaration:', 0, 1)
        pdf.set_font('helvetica', '', 9)
        pdf.multi_cell(0, 5, 'This report is dynamically generated based on verified IoT sensor telemetry and automated irrigation schedules. It is certified for government subsidy claims and internal farm audits.')

    # ─── MASTER ORCHESTRATOR ───────────────────────────────────────────────────

    @staticmethod
    def generate_dynamic_report(db: Session, request: DynamicReportRequest):
        # 1. Fetch Context
        farm = db.query(Farm).filter(Farm.id == request.farm_id).first()
        if not farm: raise ValueError("Farm not found")
        user = farm.owner
        zones = db.query(Zone).join(Acre).filter(Acre.farm_id == request.farm_id).all()
        zone_ids = [z.id for z in zones]
        
        logs = db.query(IrrigationLog).filter(
            IrrigationLog.zone_id.in_(zone_ids),
            IrrigationLog.start_time >= request.start_date,
            IrrigationLog.start_time <= request.end_date
        ).order_by(IrrigationLog.start_time.asc()).all()
        
        total_water = sum([log.water_used for log in logs if log.water_used])
        total_duration = sum([log.duration_minutes for log in logs if log.duration_minutes])
        
        # 2. Register Report Record
        report_id = uuid.uuid4()
        report_title = f"{request.theme.value} Diary - {farm.name}"
        if request.title_suffix: report_title += f" ({request.title_suffix})"
        
        db_report = Report(
            id=report_id,
            farm_id=request.farm_id,
            report_type=ReportType.CUSTOM,
            status=ReportStatus.GENERATING,
            title=report_title,
            start_date=request.start_date,
            end_date=request.end_date
        )
        db.add(db_report)
        db.commit()

        try:
            # 3. Assemble Components
            pdf = DynamicFarmPDF()
            # Theme logic could be applied here (e.g. font sizes, margins)
            
            pdf.add_page()
            
            for module in request.modules:
                if module == ReportModule.HEADER:
                    ReportService._handle_header(pdf, farm, user, request.start_date, request.end_date)
                elif module == ReportModule.STAT_CARDS:
                    ReportService._handle_stat_cards(pdf, total_water, total_duration, len(logs))
                elif module == ReportModule.CHART_WATER:
                    ReportService._handle_chart_water(pdf, logs, report_id)
                elif module == ReportModule.TABLE_ZONES:
                    ReportService._handle_table_zones(pdf, db, zones, request.start_date, request.end_date)
                elif module == ReportModule.CERTIFICATION:
                    ReportService._handle_certification(pdf)
            
            # 4. Save
            filename = f"report_dynamic_{report_id}.pdf"
            BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
            filepath = os.path.join(BASE_DIR, "static", "reports", filename)
            pdf.output(filepath)
            
            db_report.status = ReportStatus.GENERATED
            db_report.file_path = f"/static/reports/{filename}"
            db.commit()
            
            return db_report
        except Exception as e:
            db_report.status = ReportStatus.FAILED
            db.commit()
            raise e

    # ─── LEGACY COMPATIBILITY ──────────────────────────────────────────────────

    @staticmethod
    def get_yearly_report(db: Session, farm_id: UUID4, year: int):
        request = DynamicReportRequest(
            farm_id=farm_id,
            start_date=datetime(year, 1, 1),
            end_date=datetime(year, 12, 31, 23, 59, 59),
            modules=[m for m in ReportModule],
            title_suffix=f"Yearly {year}"
        )
        return ReportService.generate_dynamic_report(db, request)

    @staticmethod
    def get_monthly_report(db: Session, farm_id: UUID4, year: int, month: int):
        start_date = datetime(year, month, 1)
        if month == 12: end_date = datetime(year + 1, 1, 1) - timedelta(seconds=1)
        else: end_date = datetime(year, month + 1, 1) - timedelta(seconds=1)
        
        request = DynamicReportRequest(
            farm_id=farm_id,
            start_date=start_date,
            end_date=end_date,
            modules=[ReportModule.HEADER, ReportModule.STAT_CARDS, ReportModule.CHART_WATER, ReportModule.TABLE_ZONES, ReportModule.CERTIFICATION],
            title_suffix=f"Monthly {month}/{year}"
        )
        return ReportService.generate_dynamic_report(db, request)

    @staticmethod
    def get_custom_report(db: Session, farm_id: UUID4, start_date: datetime, end_date: datetime):
        request = DynamicReportRequest(
            farm_id=farm_id,
            start_date=start_date,
            end_date=end_date,
            modules=[m for m in ReportModule],
            title_suffix="Custom Range"
        )
        return ReportService.generate_dynamic_report(db, request)
