class AppLocalizations {
  static final Map<String, Map<String, String>> _translations = {
    // English (Default)
    'English': {
      'Home': 'Home',
      'Irrigate': 'Irrigate',
      'Control': 'Control',
      'AI Aura': 'AI Aura',
      'Chat': 'Chat',
      'Dashboard': 'Dashboard',
      'Good Morning': 'Good Morning',
      'Crop Guide': 'Crop Guide',
      'Farm Diary': 'Farm Diary',
      'History': 'History',
      'Advanced': 'Advanced',
      'Settings': 'Settings',
      'Quick Access': 'Quick Access',
      'Farm Health Score': 'Farm Health Score',
      'Healthy': 'Healthy',
      'Temperature': 'Temperature',
      'Rain Today': 'Rain Today',
      'Water Usage': 'Water Usage',
      'AI Crop Advisory': 'AI Crop Advisory',
      'zones active': 'zones active',
      'AI Assistant': 'AI Assistant',
      'Irrigation Control': 'Irrigation Control',
      'Analytics': 'Analytics',
      'Timeline': 'Timeline',
      'Add Log': 'Add Log',
      'New Season Planning': 'New Season Planning',
      'Start AI Planning': 'Start AI Planning',
      'Recommended Crops': 'Recommended Crops',
      'Ask anything about your farm...': 'Ask anything about your farm...',
      'Select Language': 'Select Language',
      'Choose your preferred language for Aura AI insights and application text.': 'Choose your preferred language for Aura AI insights and application text.',
      'Notifications': 'Notifications',
      'Clear All': 'Clear All',
      'No Notifications': 'No Notifications',
    },
    // Hindi
    'Hindi': {
      'Home': 'होम',
      'Irrigate': 'सिंचाई',
      'Control': 'नियंत्रण',
      'AI Aura': 'AI Aura',
      'Chat': 'चैट',
      'Dashboard': 'डैशबोर्ड',
      'Good Morning': 'सुप्रभात',
      'Crop Guide': 'फसल गाइड',
      'Farm Diary': 'खेत डायरी',
      'History': 'इतिहास',
      'Advanced': 'उन्नत',
      'Settings': 'सेटिंग्स',
      'Quick Access': 'त्वरित पहुंच',
      'Farm Health Score': 'खेत स्वास्थ्य स्कोर',
      'Healthy': 'स्वस्थ',
      'Temperature': 'तापमान',
      'Rain Today': 'आज की बारिश',
      'Water Usage': 'जल उपयोग',
      'AI Crop Advisory': 'AI फसल सलाह',
      'zones active': 'सक्रिय क्षेत्र',
      'AI Assistant': 'AI सहायक',
      'Irrigation Control': 'सिंचाई नियंत्रण',
      'Analytics': 'एनालिटिक्स',
      'Timeline': 'समयरेखा',
      'Add Log': 'लॉग जोड़ें',
      'New Season Planning': 'नई सीज़न की योजना',
      'Start AI Planning': 'AI योजना शुरू करें',
      'Recommended Crops': 'अनुशंसित फसलें',
      'Ask anything about your farm...': 'अपने खेत के बारे में कुछ भी पूछें...',
      'Select Language': 'भाषा चुनें',
      'Choose your preferred language for Aura AI insights and application text.': 'Aura AI अंतर्दृष्टि और एप्लिकेशन टेक्स्ट के लिए अपनी पसंदीदा भाषा चुनें।',
      'Notifications': 'सूचनाएं',
      'Clear All': 'सभी साफ करें',
      'No Notifications': 'कोई सूचना नहीं',
    },
    // Telugu
    'Telugu': {
      'Home': 'ముఖపుట',
      'Irrigate': 'నీటిపారుదల',
      'Control': 'నియంత్రణ',
      'AI Aura': 'AI Aura',
      'Chat': 'చాట్',
      'Dashboard': 'డ్యాష్‌బోర్డ్',
      'Good Morning': 'శుభోదయం',
      'Crop Guide': 'పంట గైడ్',
      'Farm Diary': 'వ్యవసాయ డైరీ',
      'History': 'చరిత్ర',
      'Advanced': 'అధునాతన',
      'Settings': 'సెట్టింగ్‌లు',
      'Quick Access': 'క్విక్ యాక్సెస్',
      'Farm Health Score': 'పొలం ఆరోగ్య మార్కు',
      'Healthy': 'ఆరోగ్యంగా ఉంది',
      'Temperature': 'ఉష్ణోగ్రత',
      'Rain Today': 'నేటి వర్షం',
      'Water Usage': 'నీటి వాడకం',
      'AI Crop Advisory': 'AI పంట సలహా',
      'zones active': 'యాక్టివ్ జోన్లు',
      'AI Assistant': 'AI అసిస్టెంట్',
      'Irrigation Control': 'నీటిపారుదల నియంత్రణ',
      'Analytics': 'విశ్లేషణలు',
      'Timeline': 'కాలక్రమం',
      'Add Log': 'లాగ్‌ని జోడించండి',
      'New Season Planning': 'కొత్త సీజన్ ప్రణాళిక',
      'Start AI Planning': 'AI ప్రణాళికను ప్రారంభించండి',
      'Recommended Crops': 'సిఫార్సు చేయబడిన పంటలు',
      'Ask anything about your farm...': 'మీ పొలం గురించి ఏదైనా అడగండి...',
      'Select Language': 'భాషను ఎంచుకోండి',
      'Choose your preferred language for Aura AI insights and application text.': 'Aura AI అంతర్దృష్టుల కోసం మీ ప్రాధాన్య భాషను ఎంచుకోండి.',
      'Notifications': 'నోటిఫికేషన్‌లు',
      'Clear All': 'అన్నీ తుడిచివేయి',
      'No Notifications': 'నోటిఫికేషన్‌లు లేవు',
    },
    // Kannada
    'Kannada': {
      'Home': 'ಮುಖಪುಟ',
      'Irrigate': 'ನೀರಾವರಿ',
      'Control': 'ನಿಯಂತ್ರಣ',
      'AI Aura': 'AI Aura',
      'Chat': 'ಚಾಟ್',
      'Dashboard': 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
      'Good Morning': 'ಶುಭೋದಯ',
      'Crop Guide': 'ಬೆಳೆ ಮಾರ್ಗದರ್ಶಿ',
      'Farm Diary': 'ಕೃಷಿ ಡೈರಿ',
      'History': 'ಇತಿಹಾಸ',
      'Advanced': 'ಸುಧಾರಿತ',
      'Settings': 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
      'Quick Access': 'ತ್ವರಿತ ಪ್ರವೇಶ',
      'Farm Health Score': 'ಕೃಷಿ ಆರೋಗ್ಯ ಸ್ಕೋರ್',
      'Healthy': 'ಆರೋದ್ಯಕರ',
      'Temperature': 'ತಾಪಮಾನ',
      'Rain Today': 'ಇಂದಿನ ಮಳೆ',
      'Water Usage': 'ನೀರಿನ ಬಳಕೆ',
      'AI Crop Advisory': 'AI ಬೆಳೆ ಸಲಹೆ',
      'zones active': 'ಸಕ್ರಿಯ ವಲಯಗಳು',
      'AI Assistant': 'AI ಸಹಾಯಕ',
      'Irrigation Control': 'ನೀರಾವರಿ ನಿಯಂತ್ರಣ',
      'Analytics': 'ವಿಶ್ಲೇಷಣೆ',
      'Timeline': 'ಟೈಮ್‌ಲೈನ್',
      'Add Log': 'ಲಾಗ್ ಸೇರಿಸಿ',
      'New Season Planning': 'ಹೊಸ ಋತುವಿನ ಯೋಜನೆ',
      'Start AI Planning': 'AI ಯೋಜನೆ ಪ್ರಾರಂಭಿಸಿ',
      'Recommended Crops': 'ಶಿಫಾರಸು ಮಾಡಿದ ಬೆಳೆಗಳು',
      'Ask anything about your farm...': 'ನಿಮ್ಮ ಕೃಷಿ ಬಗ್ಗೆ ಏನನ್ನಾದರೂ ಕೇಳಿ...',
      'Select Language': 'ಭಾಷೆ ಆಯ್ಕೆಮಾಡಿ',
      'Choose your preferred language for Aura AI insights and application text.': 'Aura AI ಒಳನೋಟಗಳಿಗಾಗಿ ನಿಮ್ಮ ಆದ್ಯತೆಯ ಭಾಷೆಯನ್ನು ಆರಿಸಿ.',
      'Notifications': 'ಅಧಿಸೂಚನೆಗಳು',
      'Clear All': 'ಎಲ್ಲವನ್ನೂ ಅಳಿಸಿ',
      'No Notifications': 'ಯಾವುದೇ ಅಧಿಸೂಚನೆಗಳಿಲ್ಲ',
    },
  };

  static String get(String key, String language) {
    if (_translations.containsKey(language) && _translations[language]!.containsKey(key)) {
      return _translations[language]![key]!;
    }
    if (_translations['English']!.containsKey(key)) {
      return _translations['English']![key]!;
    }
    return key;
  }
}
